name: Perfume Shop CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  # 1️⃣ Build and test Node.js app
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx jest

  # 2️⃣ Build Docker image and push to Docker Hub
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mabaddi96/perfume-shop:${{ github.sha }} .
          docker tag mabaddi96/perfume-shop:${{ github.sha }} mabaddi96/perfume-shop:latest
          docker push mabaddi96/perfume-shop:${{ github.sha }}
          docker push mabaddi96/perfume-shop:latest

  # 3️⃣ Deploy to OpenShift (create deployment & route if missing)
  deploy-to-openshift:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: muhammadsaleh96-dev

      - name: Ensure deployment exists
        run: |
          if ! oc get deployment perfume-shop -n muhammadsaleh96-dev; then
            echo "Deployment not found. Creating..."
            oc create deployment perfume-shop --image=mabaddi96/perfume-shop:latest -n muhammadsaleh96-dev
          else
            echo "Deployment already exists."
          fi

      - name: Ensure route exists
        run: |
          if ! oc get route perfume-shop -n muhammadsaleh96-dev; then
            echo "Route not found. Creating..."
            oc expose deployment perfume-shop --port=8080 --name=perfume-shop -n muhammadsaleh96-dev
          else
            echo "Route already exists."
          fi

      - name: Update deployment image
        run: |
          oc set image deployment/perfume-shop \
          perfume-shop=mabaddi96/perfume-shop:latest
          oc scale deployment perfume-shop --replicas=1 -n muhammadsaleh96-dev

      - name: Wait for rollout and pod readiness
        run: |
          echo "Waiting for deployment rollout..."
          if ! oc rollout status deployment/perfume-shop --timeout=5m; then
            echo "Rollout failed! Rolling back..."
            oc rollout undo deployment/perfume-shop
            oc rollout status deployment/perfume-shop
            echo "Deployment failed and rollback triggered"
            exit 1
          fi

          echo "Checking for at least one ready pod..."
          until [ "$(oc get pods -n muhammadsaleh96-dev -l app=perfume-shop -o jsonpath='{.items[0].status.containerStatuses[0].ready}')" == "true" ]; do
            echo "Pod not ready yet. Waiting..."
            sleep 5
          done

          echo "Deployment successful and pod is ready!"
          