name: Perfume Shop CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t mabaddi96/perfume-shop:${{ github.sha }} .
          docker tag mabaddi96/perfume-shop:${{ github.sha }} mabaddi96/perfume-shop:latest
      - name: Push Docker image
        run: |
          docker push mabaddi96/perfume-shop:${{ github.sha }}
          docker push mabaddi96/perfume-shop:latest

  deploy-to-openshift:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v2
        with:
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      - name: Set project namespace
        run: oc project muhammadsaleh96-dev
      - name: Update deployment image
        run: |
          oc set image deployment/perfume-shop \
          perfume-shop=mabaddi96/perfume-shop:latest
      - name: Wait for rollout or rollback on failure
        run: |
          if ! oc rollout status deployment/perfume-shop --timeout=2m; then
            echo "Rollout failed! Rolling back to previous deployment..."
            oc rollout undo deployment/perfume-shop
            oc rollout status deployment/perfume-shop
            # Send email notification
            echo "Deployment failed and rollback triggered" | mail -s "Perfume Shop Deployment Alert" -S smtp="${{ secrets.EMAIL_SMTP_SERVER }}" -S smtp-auth=login -S smtp-auth-user="${{ secrets.EMAIL_USERNAME }}" -S smtp-auth-password="${{ secrets.EMAIL_PASSWORD }}" -S smtp-use-starttls <<< "${{ secrets.EMAIL_RECIPIENT }}"
          else
            echo "Deployment successful!"
            # Send success email
            echo "Deployment succeeded" | mail -s "Perfume Shop Deployment Success" -S smtp="${{ secrets.EMAIL_SMTP_SERVER }}" -S smtp-auth=login -S smtp-auth-user="${{ secrets.EMAIL_USERNAME }}" -S smtp-auth-password="${{ secrets.EMAIL_PASSWORD }}" -S smtp-use-starttls <<< "${{ secrets.EMAIL_RECIPIENT }}"
